version: '3'
services:
  wordpress:
    image: wordpress:5.2-php7.3-fpm-alpine
    depends_on:
      - wordpress_database
    volumes:
      - wordpress_data:/var/www/html

  wordpress_database:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: my_wordpress_password

  wordpress_webserver:
    image: nginx:1.14-alpine
    depends_on:
      - wordpress
    volumes:
      - ./docker/wordpress/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress_data:/var/www/html
    ports:
      - 80:80

  wordpress_toolbox:
    build: ./docker/wordpress/toolbox/
    volumes:
      - wordpress_data:/wordpress
    working_dir: /wordpress
    depends_on:
      - wordpress_database
    environment:
      WORDPRESS_LOCALE: en_US
      WORDPRESS_DB_HOST: wordpress_database
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: my_wordpress_password
      WORDPRESS_WEBSITE_TITLE: "My blog"
      # WORDPRESS_WEBSITE_URL: "http://example.com"
      # WORDPRESS_WEBSITE_URL_WITHOUT_HTTP: "example.com"
      WORDPRESS_WEBSITE_URL: "http://localhost"
      WORDPRESS_WEBSITE_URL_WITHOUT_HTTP: "localhost"
      WORDPRESS_WEBSITE_POST_URL_STRUCTURE: "/%year%/%monthnum%/%day%/%postname%/"
      WORDPRESS_ADMIN_USER: "admin_user"
      WORDPRESS_ADMIN_PASSWORD: "admin_password"
      WORDPRESS_ADMIN_EMAIL: "test@example.com"

volumes:
  db_data: {}
  wordpress_data: {}
